@echo off
echo Starting Backend Server...
cd /d "E:\Archi\Backend"
echo Installing required dependencies if needed...
pip install -r requirements.txt
echo Starting the server on http://localhost:8001...
python -m uvicorn main:app --host 0.0.0.0 --port 8001
pause