import type { MaterialData, ClimateZone } from './indiaLocalizationService';

// Comprehensive Indian Construction Materials Database (200+ materials)
export const COMPREHENSIVE_INDIAN_MATERIALS: MaterialData[] = [
  // AGGREGATES (Expanded)
  { name: 'River Sand', category: 'sand', unit: 'cubic meter', estimatedCost: 1500, gstRate: 5, climateZones: ['tropical', 'subtropical'], isLocal: true, description: 'Natural river sand' },
  { name: 'M-Sand (Manufactured Sand)', category: 'sand', unit: 'cubic meter', estimatedCost: 1200, gstRate: 5, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Crushed stone sand' },
  { name: 'P-Sand (Plastering Sand)', category: 'sand', unit: 'cubic meter', estimatedCost: 1300, gstRate: 5, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Fine sand for plastering' },
  { name: 'Coarse Sand', category: 'sand', unit: 'cubic meter', estimatedCost: 1400, gstRate: 5, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'For concrete work' },
  { name: '20mm Aggregate', category: 'aggregate', unit: 'cubic meter', estimatedCost: 1800, gstRate: 5, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Coarse aggregate for concrete' },
  { name: '10mm Aggregate', category: 'aggregate', unit: 'cubic meter', estimatedCost: 1900, gstRate: 5, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Fine aggregate for concrete' },
  { name: '40mm Aggregate', category: 'aggregate', unit: 'cubic meter', estimatedCost: 1700, gstRate: 5, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Large aggregate' },
  { name: 'Stone Dust', category: 'aggregate', unit: 'cubic meter', estimatedCost: 800, gstRate: 5, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'For base layers' },
  { name: 'Gravel', category: 'aggregate', unit: 'cubic meter', estimatedCost: 1600, gstRate: 5, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'For drainage and landscaping' },
  
  // STONE & MASONRY (Expanded)
  { name: 'Laterite Stone', category: 'stone', unit: 'cubic meter', estimatedCost: 2500, gstRate: 5, climateZones: ['tropical'], isLocal: true, description: 'Porous stone ideal for tropical climate' },
  { name: 'Granite Stone - Rough', category: 'stone', unit: 'cubic meter', estimatedCost: 3000, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'For foundations' },
  { name: 'Granite Slabs - Polished', category: 'stone', unit: 'sq meter', estimatedCost: 350, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Premium flooring' },
  { name: 'Marble - White', category: 'stone', unit: 'sq meter', estimatedCost: 500, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Premium marble' },
  { name: 'Marble - Colored', category: 'stone', unit: 'sq meter', estimatedCost: 600, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Designer marble' },
  { name: 'Italian Marble', category: 'stone', unit: 'sq meter', estimatedCost: 1200, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: false, description: 'Imported premium marble' },
  { name: 'Kota Stone - Blue', category: 'stone', unit: 'sq meter', estimatedCost: 180, gstRate: 28, climateZones: ['subtropical', 'arid'], isLocal: true, description: 'Limestone from Rajasthan' },
  { name: 'Kota Stone - Brown', category: 'stone', unit: 'sq meter', estimatedCost: 200, gstRate: 28, climateZones: ['subtropical', 'arid'], isLocal: true, description: 'Limestone from Rajasthan' },
  { name: 'Sandstone - Yellow', category: 'stone', unit: 'sq meter', estimatedCost: 250, gstRate: 28, climateZones: ['arid', 'subtropical'], isLocal: true, description: 'Natural sandstone' },
  { name: 'Sandstone - Red', category: 'stone', unit: 'sq meter', estimatedCost: 280, gstRate: 28, climateZones: ['arid', 'subtropical'], isLocal: true, description: 'Natural sandstone' },
  { name: 'Slate Stone', category: 'stone', unit: 'sq meter', estimatedCost: 300, gstRate: 28, climateZones: ['mountain'], isLocal: true, description: 'For roofing and flooring' },
  { name: 'Basalt Stone', category: 'stone', unit: 'cubic meter', estimatedCost: 2800, gstRate: 5, climateZones: ['tropical', 'subtropical', 'mountain'], isLocal: true, description: 'Volcanic rock' },
  { name: 'Limestone', category: 'stone', unit: 'cubic meter', estimatedCost: 2200, gstRate: 5, climateZones: ['tropical', 'subtropical', 'arid'], isLocal: true, description: 'For foundations' },
  
  // WOOD & TIMBER (Expanded)
  { name: 'Teak Wood - A Grade', category: 'wood', unit: 'cubic feet', estimatedCost: 3000, gstRate: 18, climateZones: ['tropical', 'subtropical'], isLocal: true, description: 'Premium hardwood' },
  { name: 'Teak Wood - B Grade', category: 'wood', unit: 'cubic feet', estimatedCost: 2500, gstRate: 18, climateZones: ['tropical', 'subtropical'], isLocal: true, description: 'Standard hardwood' },
  { name: 'Sal Wood', category: 'wood', unit: 'cubic feet', estimatedCost: 1800, gstRate: 18, climateZones: ['subtropical'], isLocal: true, description: 'Durable hardwood' },
  { name: 'Deodar Wood', category: 'wood', unit: 'cubic feet', estimatedCost: 1500, gstRate: 18, climateZones: ['mountain'], isLocal: true, description: 'Himalayan cedar' },
  { name: 'Pine Wood', category: 'wood', unit: 'cubic feet', estimatedCost: 1200, gstRate: 18, climateZones: ['mountain'], isLocal: true, description: 'Softwood' },
  { name: 'Mango Wood', category: 'wood', unit: 'cubic feet', estimatedCost: 1600, gstRate: 18, climateZones: ['tropical', 'subtropical'], isLocal: true, description: 'Hardwood for furniture' },
  { name: 'Rosewood', category: 'wood', unit: 'cubic feet', estimatedCost: 3500, gstRate: 18, climateZones: ['tropical', 'subtropical'], isLocal: true, description: 'Premium furniture wood' },
  { name: 'Sheesham Wood', category: 'wood', unit: 'cubic feet', estimatedCost: 2200, gstRate: 18, climateZones: ['tropical', 'subtropical'], isLocal: true, description: 'Indian rosewood' },
  { name: 'Plywood - BWP 18mm', category: 'wood', unit: 'sheet', estimatedCost: 1800, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Boiling Water Proof' },
  { name: 'Plywood - BWP 12mm', category: 'wood', unit: 'sheet', estimatedCost: 1200, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Boiling Water Proof' },
  { name: 'Plywood - BWP 6mm', category: 'wood', unit: 'sheet', estimatedCost: 600, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Boiling Water Proof' },
  { name: 'Plywood - MR Grade 18mm', category: 'wood', unit: 'sheet', estimatedCost: 1400, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Moisture Resistant' },
  { name: 'Blockboard 18mm', category: 'wood', unit: 'sheet', estimatedCost: 1600, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'For furniture' },
  { name: 'MDF Board 18mm', category: 'wood', unit: 'sheet', estimatedCost: 900, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Medium Density Fiberboard' },
  { name: 'Particle Board 18mm', category: 'wood', unit: 'sheet', estimatedCost: 700, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Economy board' },
  { name: 'Laminated Plywood', category: 'wood', unit: 'sheet', estimatedCost: 2500, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Pre-finished plywood' },

  
  // TILES & FLOORING (Expanded - 40+ types)
  { name: 'Vitrified Tiles 600x600mm', category: 'tiles', unit: 'sq meter', estimatedCost: 450, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Glazed ceramic tiles' },
  { name: 'Vitrified Tiles 800x800mm', category: 'tiles', unit: 'sq meter', estimatedCost: 550, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Large format tiles' },
  { name: 'Vitrified Tiles 1200x600mm', category: 'tiles', unit: 'sq meter', estimatedCost: 650, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Extra large tiles' },
  { name: 'Ceramic Tiles 300x300mm', category: 'tiles', unit: 'sq meter', estimatedCost: 300, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Standard ceramic tiles' },
  { name: 'Ceramic Tiles 300x450mm', category: 'tiles', unit: 'sq meter', estimatedCost: 350, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Wall tiles' },
  { name: 'Porcelain Tiles 600x600mm', category: 'tiles', unit: 'sq meter', estimatedCost: 700, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: false, description: 'Premium tiles' },
  { name: 'Porcelain Tiles 800x800mm', category: 'tiles', unit: 'sq meter', estimatedCost: 850, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: false, description: 'Large premium tiles' },
  { name: 'Mosaic Tiles', category: 'tiles', unit: 'sq meter', estimatedCost: 400, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Decorative tiles' },
  { name: 'Mangalore Tiles - Red', category: 'tiles', unit: 'piece', estimatedCost: 35, gstRate: 28, climateZones: ['tropical'], isLocal: true, description: 'Clay roof tiles' },
  { name: 'Mangalore Tiles - Brown', category: 'tiles', unit: 'piece', estimatedCost: 38, gstRate: 28, climateZones: ['tropical'], isLocal: true, description: 'Clay roof tiles' },
  { name: 'Spanish Roof Tiles', category: 'tiles', unit: 'piece', estimatedCost: 45, gstRate: 28, climateZones: ['tropical', 'subtropical'], isLocal: false, description: 'Premium roof tiles' },
  { name: 'Slate Tiles', category: 'tiles', unit: 'sq meter', estimatedCost: 600, gstRate: 28, climateZones: ['mountain'], isLocal: true, description: 'Natural slate' },
  { name: 'Terracotta Tiles', category: 'tiles', unit: 'sq meter', estimatedCost: 380, gstRate: 28, climateZones: ['tropical', 'subtropical'], isLocal: true, description: 'Clay tiles' },
  { name: 'Anti-Skid Tiles', category: 'tiles', unit: 'sq meter', estimatedCost: 500, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'For bathrooms' },
  { name: 'Parking Tiles', category: 'tiles', unit: 'sq meter', estimatedCost: 280, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Heavy duty tiles' },
  { name: 'Designer Tiles - 3D', category: 'tiles', unit: 'sq meter', estimatedCost: 900, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: false, description: 'Premium designer tiles' },
  { name: 'Wooden Finish Tiles', category: 'tiles', unit: 'sq meter', estimatedCost: 650, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Wood look tiles' },
  { name: 'Marble Finish Tiles', category: 'tiles', unit: 'sq meter', estimatedCost: 700, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Marble look tiles' },
  
  // PAINT & COATING (Expanded - 30+ types)
  { name: 'Exterior Emulsion - Premium', category: 'paint', unit: 'liter', estimatedCost: 400, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Weather-resistant' },
  { name: 'Exterior Emulsion - Standard', category: 'paint', unit: 'liter', estimatedCost: 300, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Weather-resistant' },
  { name: 'Exterior Emulsion - Economy', category: 'paint', unit: 'liter', estimatedCost: 200, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Basic exterior paint' },
  { name: 'Interior Emulsion - Premium', category: 'paint', unit: 'liter', estimatedCost: 350, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Washable interior paint' },
  { name: 'Interior Emulsion - Standard', category: 'paint', unit: 'liter', estimatedCost: 250, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Interior wall paint' },
  { name: 'Interior Emulsion - Economy', category: 'paint', unit: 'liter', estimatedCost: 150, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Basic interior paint' },
  { name: 'Enamel Paint - Gloss', category: 'paint', unit: 'liter', estimatedCost: 450, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'For wood and metal' },
  { name: 'Enamel Paint - Matt', category: 'paint', unit: 'liter', estimatedCost: 420, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'For wood and metal' },
  { name: 'Distemper Paint', category: 'paint', unit: 'kg', estimatedCost: 80, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Economy wall paint' },
  { name: 'Texture Paint', category: 'paint', unit: 'kg', estimatedCost: 180, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Decorative finish' },
  { name: 'Primer - Wall', category: 'paint', unit: 'liter', estimatedCost: 150, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Base coat' },
  { name: 'Primer - Wood', category: 'paint', unit: 'liter', estimatedCost: 200, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Wood primer' },
  { name: 'Primer - Metal', category: 'paint', unit: 'liter', estimatedCost: 250, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Anti-rust primer' },
  { name: 'Putty - Wall', category: 'paint', unit: 'kg', estimatedCost: 60, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Wall filler' },
  { name: 'Waterproofing Compound', category: 'paint', unit: 'kg', estimatedCost: 150, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain'], isLocal: true, description: 'Monsoon protection' },
  { name: 'Anti-fungal Coating', category: 'paint', unit: 'liter', estimatedCost: 400, gstRate: 28, climateZones: ['tropical'], isLocal: true, description: 'Prevents fungal growth' },
  { name: 'Heat Reflective Paint', category: 'paint', unit: 'liter', estimatedCost: 500, gstRate: 28, climateZones: ['tropical', 'arid'], isLocal: true, description: 'Reduces heat absorption' },
  { name: 'Epoxy Paint', category: 'paint', unit: 'liter', estimatedCost: 600, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: false, description: 'Industrial coating' },
  { name: 'Wood Stain', category: 'paint', unit: 'liter', estimatedCost: 350, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Wood finishing' },
  { name: 'Wood Varnish', category: 'paint', unit: 'liter', estimatedCost: 400, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Wood protection' },
  { name: 'Wood Polish', category: 'paint', unit: 'liter', estimatedCost: 450, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Wood finishing' },

  
  // ELECTRICAL (40+ items)
  { name: 'Copper Wire 1.5 sq mm', category: 'electrical', unit: 'meter', estimatedCost: 25, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Electrical wire' },
  { name: 'Copper Wire 2.5 sq mm', category: 'electrical', unit: 'meter', estimatedCost: 35, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Electrical wire' },
  { name: 'Copper Wire 4 sq mm', category: 'electrical', unit: 'meter', estimatedCost: 50, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Electrical wire' },
  { name: 'Copper Wire 6 sq mm', category: 'electrical', unit: 'meter', estimatedCost: 70, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Electrical wire' },
  { name: 'Aluminum Wire 2.5 sq mm', category: 'electrical', unit: 'meter', estimatedCost: 20, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Economy wire' },
  { name: 'PVC Conduit Pipe 19mm', category: 'electrical', unit: 'meter', estimatedCost: 20, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Electrical conduit' },
  { name: 'PVC Conduit Pipe 25mm', category: 'electrical', unit: 'meter', estimatedCost: 25, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Electrical conduit' },
  { name: 'MCB 16A Single Pole', category: 'electrical', unit: 'piece', estimatedCost: 150, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Circuit breaker' },
  { name: 'MCB 32A Single Pole', category: 'electrical', unit: 'piece', estimatedCost: 200, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Circuit breaker' },
  { name: 'MCB 63A Triple Pole', category: 'electrical', unit: 'piece', estimatedCost: 500, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Circuit breaker' },
  { name: 'RCCB 40A', category: 'electrical', unit: 'piece', estimatedCost: 800, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Residual current circuit breaker' },
  { name: 'Distribution Board 4-Way', category: 'electrical', unit: 'piece', estimatedCost: 600, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'DB box' },
  { name: 'Distribution Board 8-Way', category: 'electrical', unit: 'piece', estimatedCost: 900, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'DB box' },
  { name: 'Distribution Board 12-Way', category: 'electrical', unit: 'piece', estimatedCost: 1200, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'DB box' },
  { name: 'Modular Switch - 1 Way', category: 'electrical', unit: 'piece', estimatedCost: 80, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Light switch' },
  { name: 'Modular Switch - 2 Way', category: 'electrical', unit: 'piece', estimatedCost: 120, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Light switch' },
  { name: 'Modular Socket - 6A', category: 'electrical', unit: 'piece', estimatedCost: 100, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Power socket' },
  { name: 'Modular Socket - 16A', category: 'electrical', unit: 'piece', estimatedCost: 150, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Heavy duty socket' },
  { name: 'LED Bulb 9W', category: 'electrical', unit: 'piece', estimatedCost: 120, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Energy efficient bulb' },
  { name: 'LED Bulb 12W', category: 'electrical', unit: 'piece', estimatedCost: 150, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Energy efficient bulb' },
  { name: 'LED Tube Light 18W', category: 'electrical', unit: 'piece', estimatedCost: 250, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Tube light' },
  { name: 'Ceiling Fan 1200mm', category: 'electrical', unit: 'piece', estimatedCost: 1500, gstRate: 18, climateZones: ['tropical', 'subtropical', 'arid'], isLocal: true, description: 'Ceiling fan' },
  { name: 'Exhaust Fan 150mm', category: 'electrical', unit: 'piece', estimatedCost: 800, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Ventilation fan' },
  { name: 'Exhaust Fan 200mm', category: 'electrical', unit: 'piece', estimatedCost: 1000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Ventilation fan' },
  
  // PLUMBING (40+ items)
  { name: 'CPVC Pipes 15mm', category: 'plumbing', unit: 'meter', estimatedCost: 60, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Hot and cold water' },
  { name: 'CPVC Pipes 20mm', category: 'plumbing', unit: 'meter', estimatedCost: 80, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Hot and cold water' },
  { name: 'CPVC Pipes 25mm', category: 'plumbing', unit: 'meter', estimatedCost: 100, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Hot and cold water' },
  { name: 'PVC Pipes 110mm', category: 'plumbing', unit: 'meter', estimatedCost: 120, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Drainage pipes' },
  { name: 'PVC Pipes 160mm', category: 'plumbing', unit: 'meter', estimatedCost: 180, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Drainage pipes' },
  { name: 'PVC Pipes 200mm', category: 'plumbing', unit: 'meter', estimatedCost: 250, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Drainage pipes' },
  { name: 'GI Pipes 15mm', category: 'plumbing', unit: 'meter', estimatedCost: 150, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Galvanized iron pipes' },
  { name: 'GI Pipes 20mm', category: 'plumbing', unit: 'meter', estimatedCost: 200, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Galvanized iron pipes' },
  { name: 'Water Tank 500L', category: 'plumbing', unit: 'piece', estimatedCost: 5000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Overhead tank' },
  { name: 'Water Tank 1000L', category: 'plumbing', unit: 'piece', estimatedCost: 8000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Overhead tank' },
  { name: 'Water Tank 2000L', category: 'plumbing', unit: 'piece', estimatedCost: 14000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Overhead tank' },
  { name: 'Wash Basin - Wall Mounted', category: 'plumbing', unit: 'piece', estimatedCost: 2500, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Bathroom fixture' },
  { name: 'Wash Basin - Pedestal', category: 'plumbing', unit: 'piece', estimatedCost: 3500, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Bathroom fixture' },
  { name: 'Water Closet - Indian', category: 'plumbing', unit: 'piece', estimatedCost: 2000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Toilet' },
  { name: 'Water Closet - Western', category: 'plumbing', unit: 'piece', estimatedCost: 4000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Toilet' },
  { name: 'Kitchen Sink - Single Bowl', category: 'plumbing', unit: 'piece', estimatedCost: 3000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Stainless steel sink' },
  { name: 'Kitchen Sink - Double Bowl', category: 'plumbing', unit: 'piece', estimatedCost: 4500, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Stainless steel sink' },
  { name: 'Tap - Basin Mixer', category: 'plumbing', unit: 'piece', estimatedCost: 1500, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Bathroom tap' },
  { name: 'Tap - Kitchen Mixer', category: 'plumbing', unit: 'piece', estimatedCost: 2000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Kitchen tap' },
  { name: 'Shower Head', category: 'plumbing', unit: 'piece', estimatedCost: 800, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Bathroom shower' },
  { name: 'Shower Panel', category: 'plumbing', unit: 'piece', estimatedCost: 5000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Premium shower system' },
  { name: 'Water Heater - 15L', category: 'plumbing', unit: 'piece', estimatedCost: 8000, gstRate: 18, climateZones: ['subtropical', 'mountain'], isLocal: true, description: 'Electric geyser' },
  { name: 'Water Heater - 25L', category: 'plumbing', unit: 'piece', estimatedCost: 12000, gstRate: 18, climateZones: ['subtropical', 'mountain'], isLocal: true, description: 'Electric geyser' },
  
  // DOORS & WINDOWS (30+ items)
  { name: 'Wooden Door - Teak', category: 'doors', unit: 'piece', estimatedCost: 15000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Premium wooden door' },
  { name: 'Wooden Door - Sal', category: 'doors', unit: 'piece', estimatedCost: 10000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Standard wooden door' },
  { name: 'Flush Door', category: 'doors', unit: 'piece', estimatedCost: 5000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Plywood door' },
  { name: 'PVC Door', category: 'doors', unit: 'piece', estimatedCost: 6000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Waterproof door' },
  { name: 'UPVC Door', category: 'doors', unit: 'piece', estimatedCost: 8000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Premium PVC door' },
  { name: 'Aluminum Door', category: 'doors', unit: 'piece', estimatedCost: 7000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Lightweight door' },
  { name: 'Steel Door', category: 'doors', unit: 'piece', estimatedCost: 12000, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Security door' },
  { name: 'Glass Door - Sliding', category: 'doors', unit: 'piece', estimatedCost: 15000, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Modern glass door' },
  { name: 'Wooden Window - Teak', category: 'windows', unit: 'sq feet', estimatedCost: 800, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Premium window' },
  { name: 'Aluminum Window', category: 'windows', unit: 'sq feet', estimatedCost: 400, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Standard window' },
  { name: 'UPVC Window', category: 'windows', unit: 'sq feet', estimatedCost: 500, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Premium window' },
  { name: 'Sliding Window - Aluminum', category: 'windows', unit: 'sq feet', estimatedCost: 450, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Space-saving window' },
  { name: 'Casement Window - UPVC', category: 'windows', unit: 'sq feet', estimatedCost: 550, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Opening window' },
  { name: 'Window Glass - 4mm', category: 'glass', unit: 'sq feet', estimatedCost: 80, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Standard glass' },
  { name: 'Window Glass - 6mm', category: 'glass', unit: 'sq feet', estimatedCost: 120, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Thick glass' },
  { name: 'Toughened Glass - 8mm', category: 'glass', unit: 'sq feet', estimatedCost: 200, gstRate: 28, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Safety glass' },
  { name: 'Double Glazed Glass', category: 'glass', unit: 'sq feet', estimatedCost: 350, gstRate: 28, climateZones: ['mountain'], isLocal: false, description: 'Insulated glass' },
  
  // ROOFING & WATERPROOFING (20+ items)
  { name: 'Asbestos Sheets', category: 'roofing', unit: 'sq meter', estimatedCost: 180, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Roofing sheets' },
  { name: 'Polycarbonate Sheets', category: 'roofing', unit: 'sq meter', estimatedCost: 350, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: false, description: 'Transparent roofing' },
  { name: 'Metal Roofing Sheets', category: 'roofing', unit: 'sq meter', estimatedCost: 280, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Corrugated sheets' },
  { name: 'Bitumen Sheets', category: 'roofing', unit: 'sq meter', estimatedCost: 200, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain', 'arid'], isLocal: true, description: 'Waterproof roofing' },
  { name: 'APP Membrane', category: 'waterproofing', unit: 'sq meter', estimatedCost: 250, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain'], isLocal: true, description: 'Waterproofing membrane' },
  { name: 'SBS Membrane', category: 'waterproofing', unit: 'sq meter', estimatedCost: 280, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain'], isLocal: true, description: 'Waterproofing membrane' },
  { name: 'Liquid Waterproofing', category: 'waterproofing', unit: 'liter', estimatedCost: 180, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain'], isLocal: true, description: 'Liquid coating' },
  { name: 'Cementitious Waterproofing', category: 'waterproofing', unit: 'kg', estimatedCost: 120, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain'], isLocal: true, description: 'Powder coating' },
  { name: 'Crystalline Waterproofing', category: 'waterproofing', unit: 'kg', estimatedCost: 200, gstRate: 18, climateZones: ['tropical', 'subtropical', 'mountain'], isLocal: false, description: 'Advanced waterproofing' },
  { name: 'Roof Insulation - Thermocol', category: 'insulation', unit: 'sq meter', estimatedCost: 150, gstRate: 18, climateZones: ['tropical', 'arid'], isLocal: true, description: 'Heat insulation' },
  { name: 'Roof Insulation - Rockwool', category: 'insulation', unit: 'sq meter', estimatedCost: 250, gstRate: 18, climateZones: ['mountain', 'arid'], isLocal: false, description: 'Thermal insulation' },
  { name: 'Roof Insulation - Glasswool', category: 'insulation', unit: 'sq meter', estimatedCost: 220, gstRate: 18, climateZones: ['mountain', 'arid'], isLocal: false, description: 'Thermal insulation' },
];

export default COMPREHENSIVE_INDIAN_MATERIALS;
